version: '3'
services:

  postgres:
    build: ./postgres
    restart: always
    image: rspark-postgres
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - rspark_pgdata:/opt/pg-data

  rstudio:
    build: ./rstudio
    restart: always
    image: rspark-rstudio
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI

    volumes:
      - rspark_rstudio:/home/rstudio

volumes:
  rspark_rstudio:
  rspark_pgdata:

